# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.CharField(max_length=10, verbose_name='分类')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('price', models.CharField(default=0, max_length=10, verbose_name='价格/年')),
                ('pro_count', models.CharField(max_length=10, verbose_name='创建项目个数')),
                ('pro_member', models.CharField(max_length=10, verbose_name='项目成员')),
                ('pro_space', models.CharField(max_length=50, verbose_name='项目空间')),
                ('one_file', models.CharField(max_length=50, verbose_name='单文件')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '价格策略',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('desc', models.CharField(max_length=300, verbose_name='描述')),
                ('color', models.CharField(max_length=10, verbose_name='颜色')),
                ('asterisk', models.BooleanField(default=False, verbose_name='是否星标')),
                ('part_num', models.CharField(max_length=10, verbose_name='参与人数')),
                ('used_space', models.CharField(max_length=50, verbose_name='已使用空间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asterisk', models.BooleanField(default=False, verbose_name='是否星标')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目参与者',
            },
        ),
        migrations.CreateModel(
            name='UserPriceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stutic', models.IntegerField(choices=[(1, '已支付'), (2, '未支付')], verbose_name='状态')),
                ('unit_price', models.CharField(max_length=10, verbose_name='单价')),
                ('actual_price', models.CharField(max_length=10, verbose_name='实际支付')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='开始时间')),
                ('over_time', models.DateField(verbose_name='结束时间')),
                ('year_num', models.IntegerField(verbose_name='数量(年)')),
                ('order_id', models.CharField(max_length=20, verbose_name='订单号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易记录',
            },
        ),
    ]
