# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200518_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='part_num',
            field=models.CharField(default=1, max_length=10, verbose_name='参与人数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='used_space',
            field=models.CharField(default=0, max_length=50, verbose_name='已使用空间'),
        ),
    ]
